apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculationapp2--deployment
  labels:
    app: calculationapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculationapp2
  template:
    metadata:
      labels:
        app: calculationapp2
    spec:
      containers:
      - name: calculationapp2
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000

